### ISSUE TITLE
Timeline .load() .init()

### ISSUE THREAD

**Issue by fernandojsg** [mrdoob/frame.js#1]
I've checked the code in frame.js and I've just noticed that you don't use the .load function from the modules just the .init.

I'll use .load before .init to load all the resources and after all call .init to initialize everything related to the module.

I think it shouldn't be called any .init code if the rest of the .load effects are still peding because maybe a module could depends on another one.

The .load callback should be automated by the FRAME function instead of leaving it to the user, and include a load funciont on Timeline with a callback that could be used as global status of the loading (creating a progress bar and so on).

I've modified something similar to the following:

``` javascript
Timeline: function ()
{
  load: function (callback) {
    this.elementsToLoad=elements.length;
    for ( var i = 0, l = elements.length; i < l; i ++ ) {
        element[ i ].load(loadedCallback);
    }

  loadedCallBack: function (element) {
     this.elementsToLoad--;
     userLoadedElementCallback(element);
     if (this.elementsToLoad==0)
        this.init();
  }
}
```

What do you think?

**Comment by mrdoob** [comment]
Closing this because since 6449949b818bd36db2b151872e2f6f985ebcc15c the code base is now different. Open a new PR is needed.
