### ISSUE TITLE
Reuse Modules

### ISSUE THREAD

**Issue by frederickk** [mrdoob/frame.js#13]
Is it possible to reuse modules as if they were "classes"?

Example:
Say I have created BlockModule.js, which is simply a square I can attach certain parameters to. I cannot seem to reuse this module in the timeline without the last added "block" instance (to the json var) controlling (or usurping) all of the other "block" instances.

Does this make sense? I would be grateful for any insight.

Thanks,
Ken

**Comment by mrdoob** [comment]
Closing this because since 6449949b818bd36db2b151872e2f6f985ebcc15c the code base is now different. Open a new PR is needed.
