### ISSUE TITLE
Documentation - How to

### ISSUE THREAD

**Issue by gaitat** [mrdoob/frame.js#14]
Is there any type of documentation on this library. I have seen the online presentations using it and the obsidian demo but I would really like to understand the json input file and how to design using it.
This library would solve a lot of my issues.

**Comment by mrdoob** [comment]
Unfortunately it's still not ready for others to use...

**Comment by ferranpons** [comment]
Hi @mrdoob  
There are any news about this? Are you still working in this library? Or... is it abandoned? 
Thanks in advance. :pray:

**Comment by mrdoob** [comment]
I recently figured out how this library should be. I intend to reimplement it with the right structure over the next few months.

**Comment by ferranpons** [comment]
Ok, I understand. But it would be cool to have some documentation and a working version of the editor without the need of modifying it. Its just a suggestion. I'm looking forward to see a full working version anytime soon. 

Thanks anyway! And keep up the good work!  :wink:

**Comment by mrdoob** [comment]
Closing this because since 6449949b818bd36db2b151872e2f6f985ebcc15c the code base is now different. Open a new PR is needed.
