### ISSUE TITLE
additional parameters for textblock

### ISSUE THREAD

**Issue by infantilo** [mrdoob/frame.js#15]
When adding additional parameters to e.g. the text block (e.g. font size or font type) the output won't be refreshed on chaning these parameters.
`       return new FRAME.Module( {

```
        parameters: {

            text:          new FRAME.Parameter.String( 'Text', 'text' ),
            startPosition: new FRAME.Parameter.Vector3( 'Camera Start', [ 0, 0, 20 ] ),
            endPosition:   new FRAME.Parameter.Vector3( 'Camera End', [ 0, 0, 40 ] ),
            fontsize:      new FRAME.Parameter.Integer( 'Font Size', 2, 0 , 24 )

        },

        init: function () {

            var string = this.parameters.text.value;
            var fsize  = this.parameters.fontsize.value;

            if ( texts[ string ] === undefined ) {

                var shapes = THREE.FontUtils.generateShapes( string, {
                    font: "helvetiker",
                    size: fsize
                } );
```

`
Only changing the text itself will render with the new fontsize.

**Comment by mrdoob** [comment]
Hold your horses for a bit. I have a completely-refactored version almost ready to upload.

**Comment by infantilo** [comment]
great news!! Can't wait to have a look on it!

**Comment by infantilo** [comment]
May i ask, if you've any date when the next version will be available??

**Comment by mrdoob** [comment]
En of July for sure! 😇

**Comment by bforest-ariadne** [comment]
Any update on the new version? Very intrigued by the webvr version of Obsidian :)

**Comment by infantilo** [comment]
Any updates on the new version?????? ;-)

**Comment by mrdoob** [comment]
Sooooooooooon! 😁

**Comment by infantilo** [comment]
hi! May i ask if you've any news abaout the new editor????
I'd really looking forward for it.
Many thanks for reply

**Comment by mrdoob** [comment]
Closing this because since 6449949b818bd36db2b151872e2f6f985ebcc15c the code base is now different. Open a new PR is needed.
