### ISSUE TITLE
Cannot run the obsidian demo -- missing js module

### ISSUE THREAD

**Issue by alexisheloir** [mrdoob/frame.js#16]
I cannot run the obsidian dem because the FadeInModule.js is missing in the /examples/obsidian/js/modules/ directory.

127.0.0.1 - - [07/Jul/2016 10:57:30] code 404, message File not found
127.0.0.1 - - [07/Jul/2016 10:57:30] "GET /examples/obsidian/js/modules/FadeInModule.js HTTP/1.1" 404 -

**Comment by tonbz** [comment]
there is not thing to do in examples directory, Just run index.html in editor directory.
