### ISSUE TITLE
#timeline .block   in    dark.css

### ISSUE THREAD

**Issue by akinhwan** [mrdoob/frame.js#17]
I am having trouble assigning different background-colors to the #timeline .block. Which are the module blocks that appear in the timeline. They have text that says either ColorModule or ImageModule, etc on them. By default they are all purplish, but I would like to divide them into several groups so that Type1Module is Blue, Type2Module is Green, and Type3Module is Orange. 

How would I do this?

It appears that in Timeline.Module.js the dom.className is set to 'block' on line 27.

**Comment by mrdoob** [comment]
Closing this because since 6449949b818bd36db2b151872e2f6f985ebcc15c the code base is now different. Open a new PR is needed.
