### ISSUE TITLE
Frame.js versus Timeliner integration

### ISSUE THREAD

**Issue by pwkey** [mrdoob/frame.js#20]
I am looking to develop 3D enabled technical documentation/presentations, whereby there is an initial scripted animation followed by the user being able to explore and learn within the 3D environment. The scripted animation would have a voice over and hence need the ability to sync an audio track.

I noticed another three.js project implementing the Timeliner library and wondered which of Frame.js or Timeliner would be most appropriate for me to focus on?

**Comment by mrdoob** [comment]
You can use either, but at this point, you need to be very comfortable programing and solving any problem you bump into on your own.
