### ISSUE TITLE
Parameters description

### ISSUE THREAD

**Issue by fernandojsg** [mrdoob/frame.js#3]
I was thinking what could be the first feature I'll add to the sequencer, and I think could be the parameters tweaking. It will help just having a simple effect to play with it and see something more than just a player of a jsoned demo.
Thinking in what I had in my editor, I'll propose something like:

``` javascript
{
    "amount": {
        "shortname": "Amount",
        "desc": "Amount of sprites",
        "type": "i",
        "default": 20,
        "min": 1,
        "max": 50
    }
    "size": {
        "shortname": "Size",
        "desc": "Size of the sprite",
        "type": "f",
        "default": 3.5,
        "min": 1.0,
        "max": null
    }
}
```

So you could create controls for each kind of parameter. 
The basic kind of parameters that will be necessary could be:
- integer
- float
- color
- boolean
- combo/list
- texture

And of course after that you could also integrate types of the three.js like vector2, vector3 or so. But at least to start with something to create custom controls for the editor.

**Comment by mrdoob** [comment]
Closing this because since 6449949b818bd36db2b151872e2f6f985ebcc15c the code base is now different. Open a new PR is needed.
