### ISSUE TITLE
Block constraints

### ISSUE THREAD

**Issue by fernandojsg** [mrdoob/frame.js#9]
I was about to do the block constraints while moving the block after adding the .end property #8 but I got into a question. Right now you can move a block over other, but I think It shouldn't be possible right?
It guess the following constraints should be done:
- 0 < `.left` < `.right` - 2*sizeResizeDiv
- `.left`\+ 2*sizeResizeDiv < `.right` < Timelinelength
- `.left` < `.right` of the closer block (left) in the same layer 
- `.right` < `.left` of the closer block (right) in the same layer

**Comment by mrdoob** [comment]
Closing this because since 6449949b818bd36db2b151872e2f6f985ebcc15c the code base is now different. Open a new PR is needed.
